# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houseplanner', '0002_auto_20170328_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house', to='houseplanner.House'),
        ),
    ]
