# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseplanner', '0003_auto_20170328_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
