# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseplanner', '0004_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
