# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houseplanner', '0005_auto_20170328_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houseplanner.User')),
            ],
        ),
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Expense',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='transaction',
        ),
    ]
