# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseplanner', '0006_auto_20170329_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='completed',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
