# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseplanner', '0008_auto_20170329_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='endDate',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='startDate',
            new_name='start',
        ),
    ]
