# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 03:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseplanner', '0010_auto_20170330_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='endDate',
            field=models.DateField(default=datetime.date(2017, 3, 30)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='startDate',
            field=models.DateField(default=datetime.date(2017, 3, 30)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.CharField(max_length=255),
        ),
    ]
