# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseplanner', '0011_auto_20170330_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='endDate',
            field=models.DateField(null=True),
        ),
    ]
